import {
  Loader2,
  LogOut,
  Plus,
  CalendarIcon,
  CalendarClock,
  MoreHorizontal,
  Pencil,
  Trash2,
  Share,
  Square,
  CheckSquare2,
  MessageCircle,
  SendHorizontal,
  ChevronDown,
  Github,
  Link,
  ArrowLeft,
  CheckCircle,
  Share2,
  ClipboardList, ClipboardCheck,
  Clock,
  Inbox
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  logout: LogOut,
  plus: Plus,
  calendar: CalendarIcon,
  calendarClock: CalendarClock,
  more: MoreHorizontal,
  edit: Pencil,
  delete: Trash2,
  share: Share,
  square: Square,
  checkedSquare: CheckSquare2,
  comments: MessageCircle,
  send: SendHorizontal,
  arrowDown: ChevronDown,
  github: Github,
  link: Link,
  arrowLeft: ArrowLeft,
  checkCircle: CheckCircle,
  share2: Share2,
  clipboardList: ClipboardList,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  inbox: Inbox,

};
